### ISSUE TITLE
Javascript TypeError in versions >v1.0

### ISSUE THREAD

**Issue by alex-santander** [sassoftware/vscode-sas-extension#458]
**Describe the bug**
Bug exists in v1.1 and v1.2, but v1.0 works fine. 
When trying to run code, the following message appears.

```
TypeError: Cannot read properties of undefined (reading 'html5')
	at Ff._doExecution (/Users/e1218443/.vscode/extensions/sas.sas-lsp-1.2.0/client/dist/node/extension.js:210:4442)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Ff._execute (/Users/e1218443/.vscode/extensions/sas.sas-lsp-1.2.0/client/dist/node/extension.js:210:4115)
	at async y.$executeCells (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:100503)
```

![image](https://github.com/sassoftware/vscode-sas-extension/assets/142606699/d11ece48-7564-4abc-8c93-6504691924e5)

Tested on two machines, but at the same organisation - so similar config.

**Steps to reproduce**
Unable to run any SAS code at all.
Try to run anything, even a libname statement.

**Expected behavior**
Expected SAS code to run as per v1.0

**Screenshots**

**Environment (please complete the following information):**
Client OS: MacOS Monterey 12.6.7 
Extension version: v1.1 and v1.2
SAS version: 9.04.01M3P062415
SAS Server Operating System: LIN X64

**Comment by scnwwu** [comment]
Just to confirm, you're connecting via SSH right?
