### ISSUE TITLE
Internal Error Code: -32603 Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by SG-A47** [sassoftware/vscode-sas-extension#725]
**Describe the bug**
When I do a cut and paste in a HLASM-Source, this error is shown.

**Steps to reproduce**

1. Double Click on a word
2. CTRL-C cut it
3. Double Click another word
4. CTRL-V paste

**Expected behavior**
No error

**Lines from the Error screen**
[Error - 10:11:46] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
	at com.ibm.wazi.lsp.hlasm.core.parser.AST.getSymbolInformation(AST.java:112)
	at com.ibm.wazi.lsp.hlasm.core.handlers.DocumentSymbolHandler.getSymbols(DocumentSymbolHandler.java:33)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer.lambda$4(HLASMLanguageServer.java:217)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer$$Lambda$124/0x00000000148e1140.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more

**Environment (please complete the following information):**
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Datum: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Windows_NT x64 10.0.22621

**Additional context**
You can ignore this error by closing the error window, but it rises again and again.

**Comment by scnwwu** [comment]
Hi @SG-A47,
This project doesn't provide HLASM language support. What extension are you using?

**Comment by SG-A47** [comment]
IBM Z Open Editor v3.3.1
The error raises when I do some coding in an Assembler program, but the message seems to come from VSCode. There is no indication in the message that it comes from the language server.

**Comment by scnwwu** [comment]
Hi @SG-A47,
The error you posted looks from the language server. Please report to the repository of the extension, in your case https://github.com/IBM/zopeneditor-about
If you have general issues of VS Code, please report to VS Code repo, https://github.com/microsoft/vscode
This project is only for SAS extension. Thanks.
