### ISSUE TITLE
Can't connect to SAS OnDemand using VS Code Extension (or Integration Technologies Client)

### ISSUE THREAD

**Issue by tedconway** [sassoftware/vscode-sas-extension#990]
**Describe the bug**
Attempts to connect to SAS OnDemand using VS Code Extension OR via SAS Integration Technologies client time out. This ODA server I'm assigned to had a multi-day outage this week (maintenance) and is slated to be down again all day tomorrow. The interactive ODA environment is working now, but is there any chance that the SAS Integration Technologies service may not be accepting connections? I did see that I couldn't connect to the status page for the server now, which I could do during the outage. Thanks!

**Steps to reproduce**

Try to connect to SAS OnDemand using VS Code or SAS Integration Technologies client and it times out after about 5-20 seconds.

**Expected behavior**
Connection established.

**Screenshots**

**Environment (please complete the following information):**
Windows 11.
No SAS on laptop but installed latest (SAS 9.4M8-compatible) SAS Integration Technologies client as instructed.
SAS Extenstion for VS Code is V1.9.0 

**Additional context**
Here's the output from SAS Integration Technologies client test.

System.Runtime.InteropServices.COMException (0x80042002): <connectionAttempts>
	<connectionAttempt>
		<description>Connection timed out. A connection attempt failed because the SAS Server did not properly respond after a period of time, or established connection failed because connected host has failed to respond. </description>
		<status>0x8007274c</status>
		<saslogin>myemailID@myemailprovider.com</saslogin>
		<sasmachinednsname>odamid-usw2.oda.sas.com</sasmachinednsname>
		<sasport>8591</sasport>
		<sasclassid>440196D4-90F0-11D0-9F41-00A024BB830C</sasclassid>
		<sasprogid>SAS.Workspace.1.0</sasprogid>
		<threadid>3436</threadid>
		<name>test</name>
	</connectionAttempt>
</connectionAttempts>
   at SASObjectManager.IObjectFactory2.CreateObjectByServer(String Name, Boolean synchronous, IServerDef pIServerDef, String LoginName, String Password)
   at SAS.BI.Itconfig.Library.ServerTests.SASServerTest.CreateConnectionWithObjectFactoryMulti()
   at SAS.BI.Itconfig.Library.ServerTests.SASServerTest.CreateConnection()

**Comment by tedconway** [comment]
OK, thanks chris. Perhaps that's the explanation. I still can connect to ODA using SASpy, but i guess that goes down a different security path.

**Comment by cjdinger** [comment]
Yes, SASPy uses a Java-based approach and not the Windows-based IntTech client. Some special steps were needed to make that work, but it's bundled into the SASPy process.

**Comment by ShuguangSun** [comment]
Sorry for jump in. May have a try https://github.com/sassoftware/vscode-sas-extension/pull/942 with SASPy profile if you can compile the extension.

**Comment by tedconway** [comment]
@ShuguangSun: Like the concept and see you've submitted a request for review, so if this idea gets incorporated into a new SAS VS Code extension verison, I'll definitely give it a try (I can connect via SASpy)! Thanks!

**Comment by angelfish0808** [comment]
It seems that ordinary soda users basically cannot connect to soda through the vscode plug-in. I understand that at least they have to sign up for the eg course to do this, right?

**Comment by cjdinger** [comment]
@angelfish0808 An additional component is needed -- a small piece of cryptography that is included only with installed apps like SAS EG, SAS for Windows and a few others. Apologies for the gap on this, but not aware of another remedy at this time.  Enrolled students can get SAS EG via SODA.

**Comment by kimseonsaengnim** [comment]
@cjdinger I have the same issue with @tedconway. I also receive this error whenever i try to connect my VS Code to SAS

> Connection timed out. A connection attempt failed because the SAS Server did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I already have the SAS EG as well as the ITC on my Win10. I think it has something to do with SAS Integration Technologies Configuration not being able to recognize the SAS EG installed? It gives this kind of prompt whenever i open the SAS ITC:

> A valid installation of SAS could not be found.  SAS may not be installed on this machine.
There was an error accessing the current DCOM settings.

I already tried entering SAS sever definition manually, as well as adding it to the firewall, but the problem still persists. 

Can you suggest a workaround for this?

**Comment by cjdinger** [comment]
If you can verify [that this PowerShell script is working](https://github.com/sassoftware/sas-inttech-samples/blob/master/PowerShell/src/SASWorkspaceExample.ps1) (with modifications for the correct host and credentials, then you will know that your machine can connect. This would use the same mechanism as VS Code and even EG.

**Comment by FungluiKoo** [comment]
> Yes, SASPy uses a Java-based approach and not the Windows-based IntTech client. Some special steps were needed to make that work, but it's bundled into the SASPy process.

@cjdinger But since SASPy can successfully connect to remote SAS without any installation of SAS on local machine, I believe the vscode-sas-extension can also be updated to achieve that (probably by adding the encryption modules you mentioned). I hope this update would come out soon.
